# Generated by Django 2.2 on 2020-03-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covit', '0004_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_end', to='covit.Direction'),
        ),
    ]
