# Generated by Django 2.2 on 2020-03-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='direction',
            field=models.CharField(default='NS', max_length=50),
            preserve_default=False,
        ),
    ]
