# Generated by Django 2.2 on 2020-03-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='covit.Direction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='prueba@prueba.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='end_stop',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='person_end', to='covit.Stop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='initial_stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_initial', to='covit.Stop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='covit.Route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='covit.Bus_Segment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='segment',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covit.Direction'),
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
