# Generated by Django 2.2 on 2020-03-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covit', '0002_segment_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='loc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
