# Generated by Django 2.2 on 2020-03-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covit', '0002_auto_20200323_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_segment',
            name='service',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
