# Generated by Django 2.2 on 2020-03-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covit', '0003_segment_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50)),
                ('id_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covit.Route')),
            ],
        ),
    ]
